name: Build and push the latest build to production

on:
  push:
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Create Tag
        id: gen_tags
        run: |
          echo '::set-output name=tags::'"${GITHUB_REF/refs\/tags\//}"

      - name: Build and push production images
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          tags: ${{ secrets.ACR_NAME }}/contoso-website:${{ steps.gen_tags.outputs.tags }}
          push: true
